name: 01 - Building Blocks

on:
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: pass step
        run: |
          echo "I will pass"
          exit 0

      - name: Say Goodbye
        if: always()  # Ensures this step runs even if the previous step fails
        run: echo "Goodbye"

           

       
   
    


  


